[package]
name = "reeba-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5"
axum = "0.8"
axum-extra = { version = "0.10", features = ["cookie"] }
cookie = "0.18"
deadpool-postgres = "0.14"
eloquent = "2"
gcloud-sdk = { version = "0.26", features = ["google-rest-storage-v1"] }
geo-types = { version = "0.7", features = ["serde"] }
jiff = { version = "0.1", features = ["serde"] }
jsonwebtoken = { version = "9", features = ["use_pem"] }
paste = "1"
postgres-types = { version = "0.2", features = ["derive", "jiff-01"] }
rust_decimal = { version = "1", features = [
  "serde-with-float",
  "serde-with-str",
  "db-tokio-postgres",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = [
  "with-serde_json-1",
  "with-geo-types-0_7",
  "with-jiff-0_1",
] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ts-rs = "10"
ulid = { version = "1", features = ["serde"] }
utoipa = { version = "5", features = [
  "axum_extras",
  "time",
  "decimal",
  "ulid",
] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
